"use client";

import type { Recommendation } from "@/lib/api";
import { ArrowUpRight } from "lucide-react";

const PRIORITY_STYLES: Record<string, string> = {
  high: "bg-lose/10 text-lose",
  medium: "bg-warn/10 text-warn",
  low: "bg-ink-100 text-ink-600",
};

export default function Recommendations({ recommendations }: { recommendations: Recommendation[] }) {
  return (
    <div className="card p-6">
      <div className="flex items-baseline justify-between mb-4">
        <h3 className="font-semibold tracking-tight">Recommendations</h3>
        <span className="text-xs text-ink-400">Generated by Gemini agent</span>
      </div>
      <div className="space-y-4">
        {recommendations.map((r, i) => (
          <div key={i} className="flex gap-4">
            <div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-ink-100 font-mono text-sm text-ink-600">
              {i + 1}
            </div>
            <div className="flex-1">
              <div className="flex items-start justify-between gap-3">
                <h4 className="font-medium text-ink-900">{r.title}</h4>
                <span className={`shrink-0 rounded-full px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider ${PRIORITY_STYLES[r.priority]}`}>
                  {r.priority}
                </span>
              </div>
              <p className="mt-1 text-sm text-ink-600 leading-relaxed">{r.detail}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
